MODULE idlpgr
DESCRIPTION IDL interface to the PointGrey FlyCap2 API
VERSION 0.1
SOURCE David G. Grier, New York University
BUILD_DATE MAR 02 2015
FUNCTION IDLPGR_CREATECONTEXT 0 0
PROCEDURE IDLPGR_DESTROYCONTEXT 1 1
FUNCTION IDLPGR_GETNUMOFCAMERAS 1 1
FUNCTION IDLPGR_GETCAMERAFROMINDEX 1 2
PROCEDURE IDLPGR_CONNECT 2 2
PROCEDURE IDLPGR_STARTCAPTURE 1 1
PROCEDURE IDLPGR_STOPCAPTURE 1 1